In [1]:
import numpy as np
from sklearn.model_selection import KFold
x = np.array([[1, 2], [3, 4], [4, 3], [1, 2], [3, 4], [5, 6], [6, 4], [1, 2], [2, 2], [1, 2]])
y = np.array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1])
kf = KFold(n_splits = 5, shuffle = True)

for train_index, test_index in kf.split(x):
    print(train_index, test_index)

[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 3 4 6 7 8] [5 9]
[0 2 3 5 6 7 8 9] [1 4]
[0 1 3 4 5 6 7 9] [2 8]
[1 2 3 4 5 6 8 9] [0 7]
