In [1]:
def vectorize_sequences(sequences, dimension=4):
    
    print(len(sequences))
    # 形状が(len(sequences), dimension)の行列を作成し、0で埋める。
    results = np.zeros((len(sequences), dimension))
    # print(results)
    print(results.shape)
    
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
        
    return results

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [4]:
vectorize_sequences(arr)

3
(3, 4)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
arr0 = np.array([1,2,3])
arr1 = np.array([4,5,6])

In [9]:
arr = np.concatenate([[arr0, arr1]], axis = 0)

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [13]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [0, 11, 12]])

In [15]:
np.concatenate([a1, a2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 0, 11, 12]])

In [17]:
arr = np.concatenate([a1, a2], axis=1)

In [19]:
arr.mean(axis=0)

array([ 2.5,  3.5,  4.5,  3.5,  9.5, 10.5])

In [20]:
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6,  0, 11, 12]])