In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
np.reshape(arr, (1, 3))

array([[1, 2, 3]])

In [4]:
arr = np.array([1,2,3])

In [5]:
np.reshape(arr, (3, 1))

array([[1],
       [2],
       [3]])

In [6]:
arr = np.array([[2,3],[4,5]])

In [8]:
arr.sum(axis=0)

array([6, 8])